# .github/workflows/build.yml
name: Build Docker Images from Multi Repo

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Controller Repo
        uses: actions/checkout@v3

      - name: Clone Angular Frontend Repo
        run: |
          git clone https://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@github.com/Sanchalvk/Angulardockerfilecreate.git frontend

      - name: Clone Java Backend Repo
        run: |
          git clone https://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@github.com/Sanchalvk/docker-.git backend

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: sanchalkhedkar
          password: dckr_pat_yC7BqB9FPf8d_ZT9M_A4dktjrWo

      - name: Build & Push Angular Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: sanchalvk/angular-app:latest

      - name: Build & Push Java Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: sanchalvk/java-app:latest
